# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59b79baa5a8be794816a74330efd8336bd8fe3baf562ba514dca6df4df7ccfe31b1a2e77757226e221f38a832a51e97112e8d1bfe107e7de5bea7332cb668df9

test:
  secret_key_base: 06dd8deae8ac375a6b81a7ee702bdf92e5d3514ed63db97f929b8d0e6eb80ed4ae00b71ede1d0d20aa938bd704568c8864e90cd926d72d3edb6f20d8b61983f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
